config/routes.rb
Rails.application.routes.draw do

  resources :listings

  devise_for :users

  root 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
validates_uniqueness_of :heading

	def self.convert_to_utc
		day = Date.today
		time = day.to_time
		unix = time.to_i
		unix.to_s
	end

	def self.get_new_listings
		api_key = ENV["api_key"]
		response = HTTParty.get("http://polling.3taps.com/poll?auth_token=7e53474c2e150233dc488e90832debd7&anchor=1949751160&source=CRAIG&category_group=RRRR&category=RHFR&location.county=USA-CA-LOS&retvals=location,external_url,heading,body,timestamp,price,images,annotations")
		output = JSON.parse(response.body)
		properties = output["postings"] 
	end

	def self.create_new_listings(new_listings)
		if new_listings != nil
			new_listings.each do |property|
				if property["location"]["zipcode"] != nil && property["location"]["formatted_address"] != nil && property["location"]["city"] != nil
					Listing.create(external_url: property["external_url"], heading: property["heading"], 
					body: property["body"], price: property["price"], bathrooms: property["annotations"]["bathrooms"], 
					bedrooms: property["annotations"]["bedrooms"], lat: property["location"]["lat"], long: property["location"]["long"], 
					address: property["location"]["formatted_address"], zipcode: property["location"]["zipcode"].gsub(/[^\d]/, '').to_i, 
					city: property["location"]["city"])
				end
			end
		end
	end

	def self.add_images_to_listings(new_listings)
		if new_listings != nil
			new_listings.each do |property|		
				listing = Listing.where(external_url: property["external_url"]).first
				if listing != nil
					property["images"].each do |x|
						listing.images << x["full"]
						listing.save
					end
				end
			end
		end
	end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }
  validates :encrypted_password, presence: true, length: { minimum: 8  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  
  def new
  end

  def create
  end

  def update
  end

  def destroy
  end

  def edit
  end

  def index
    # Listing.get_new_listings
    # Listing.create_new_listings(Listing.get_new_listings)
    # Listing.add_images_to_listings(Listing.get_new_listings)
    twentyfive = Listing.last(25)
    @listings = []
    twentyfive.each do |x|
      if x.images.empty? == false
        @listings << x
      end
    end
    @listings = @listings.last(9).reverse
    @hash = Gmaps4rails.build_markers(@listings) do |listing, marker|
      marker.lat listing.lat
      marker.lng listing.long
    end
  end


  def show
    @listing = Listing.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Craigslist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="javascript:void(0)">MRFE</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">
      <li><a href="javascript:void(0)">Link</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
     <li class="dropdown">
      <% if user_signed_in? %>
        <a href="http://fezvrasta.github.io/bootstrap-material-design/bootstrap-elements.html" data-target="#" class="dropdown-toggle" data-toggle="dropdown">Hello, <strong><%= current_user.email %></strong>! <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
          <li> <%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li> <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
        <li>  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
       <% end %>

          <!-- <li><a href="javascript:void(0)">Something else here</a></li>
          <li class="divider"></li>
          <li class="dropdown-header">Dropdown header</li>
          <li><a href="javascript:void(0)">Separated link</a></li>
          <li><a href="javascript:void(0)">One more separated link</a></li> -->
        </ul>
      </li>
    </ul>
  </div>
</div>

	<!-- <p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>	 -->

<%= yield %>

</body>
</html>

app/views/listings/create.html.erb
<h1>Listings#create</h1>
<p>Find me in app/views/listings/create.html.erb</p>

app/views/listings/destroy.html.erb
<h1>Listings#destroy</h1>
<p>Find me in app/views/listings/destroy.html.erb</p>

app/views/listings/edit.html.erb
<h1>Listings#edit</h1>
<p>Find me in app/views/listings/edit.html.erb</p>

app/views/listings/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

	<div class="ha-bg-parallax text-center block-marginb-none" data-type="background" data-speed="20">
		<div class="ha-parallax-body">
			<div class="ha-content ha-content-whitecolor">
				<span class="headertext">Search multiple sites for the perfect place.</span><br>
				<span class="headertext">#thatincludeswestsiderentals!</span><br>
				<!-- <span class="headertext">Airbnb is too damn expensive.</span> -->
			</div>
			<div class="ha-parallax-divider-wrapper">
				<span class="ha-diamond-divider-md img-responsive"></span>
			</div>
		</div>
	</div>


<div id="DIV_1">
	<div id="DIV_2">
		<h2 id="H2_3">
			Popular cities in LA
		</h2>
		<p id="P_4">
			find a home in one of these popular areas
		</p>
	</div>
	<div id="DIV_5">
		<div id="DIV_6">
			<div id="DIV_7">
				<div id="DIV_8">
					<div id="DIV_9">
						<a href="/getaways/Los-Angeles?destination=Malibu" id="A_10"></a>
						<div id="DIV_11">
							<div id="DIV_12">
								<div id="DIV_13">
									Malibu
								</div>
							</div>
						</div>
					</div>
				</div>
				<div id="DIV_14">
					<div id="DIV_15">
						<a href="/getaways/Los-Angeles?destination=Ojai" id="A_16"></a>
						<div id="DIV_17">
							<div id="DIV_18">
								<div id="DIV_19">
									Ojai
								</div>
							</div>
						</div>
					</div>
				</div>
				<div id="DIV_20">
					<div id="DIV_21">
						<a href="/getaways/Los-Angeles?destination=Santa-Barbara" id="A_22"></a>
						<div id="DIV_23">
							<div id="DIV_24">
								<div id="DIV_25">
									Santa Barbara
								</div>
							</div>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
</div>

	<h1><center>Latest Listings</center></h1>

	<div class="jumbotron">
		<div class="map_container"> 
			<div id="map" class="gmaps4rails_map" style='width: 100%; height: 400px;'>
			</div> 
		</div>
		<script>
		handler = Gmaps.build('Google');
		handler.buildMap({ provider: {scrollwheel: false, zoomControl: false}, internal: {id: 'map'}}, function(){
			markers = handler.addMarkers(<%=raw @hash.to_json %>);
			handler.bounds.extendWith(markers);
			handler.fitMapToBounds();
		});
		</script>
	</div>

	<div class="table">
		<% @listings.each do |x| %>
		<div class="col-md-4">
			<%= link_to listing_path(x) do %>
			<div class="card">
				<div class="card-image">
					<div class="card-title">
						<%= x.bedrooms %> bedroom / <%= x.bathrooms %> bathroom for $<%= x.price %>/mo in <%= x.address.split(",")[0] %>
					</div>
					<%= image_tag(x.images[1],:class => "style_image") %>
				</div>

				<div class="card-content">
					<!%= link_to x.external_url %>
				</div>

				<div class="card-action">
					<div class="icon-preview"><i class="mdi-action-trending-neutral"></i><span><%= x.heading %></span></div>
					<div class="icon-preview"><i class="mdi-social-location-city"></i> <span><%= truncate(x.body, :length => 90) %> </span></div>
				</div>
			</div>
		</div>
		<% end %>
		<% end %>

app/views/listings/new.html.erb
<h1>Listings#new</h1>
<p>Find me in app/views/listings/new.html.erb</p>

app/views/listings/update.html.erb
<h1>Listings#update</h1>
<p>Find me in app/views/listings/update.html.erb</p>